on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # or your preferred version

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Copy build folder to EC2 via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: "build/*"
          target: "/home/ubuntu/build-temp"

      - name: SSH into EC2 and move build to web directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            echo "Connected to EC2!"
            echo "Updating EC2 server"
            sudo apt update -y
            echo "stopping ngins"
            sudo systemctl stop nginx
            echo "starting nginx"
            sudo systemctl start nginx
            sudo rm -rf /var/www/html/frontend/*
            sudo mv /home/ubuntu/build-temp/* /var/www/html/frontend/
            echo "testing nginx"
            sudo nginx -t 
            echo "nginx reloadeding"
            sudo systemctl reload nginx
            
